BEGIN 
DBMS_OUTPUT.PUT_LINE('HELLO WORLD');
END;

--------VARIABLE DECLARATION
--INT VAR=10;

TAX INT :=10
SALARY REAL := 3000.02;
HOME VARCHAR(10) := 'HELLO'; --DECLARE AND INITIALIZATION

COPY INT :=TAX*10;

---
DECLARE 
EMP_NAME CHAR(10) := 'DANIEL';
COPY CHAR(10);
BEGIN
COPY := EMP_NAME;
DBMS_OUTPUT.PUT_LINE('NAME OF THE EMPLOYEE IS: ' || COPY);
END;

---CONSTANT VARIABLE

DECLARE 
TAX CONSTANT INT :=500;
SALARY INT;
BEGIN

--TAX := TAX +100;
DBMS_OUTPUT.PUT_LINE('TAX PAYABLE IS : ' || TAX);
SALARY:=TAX*10;
DBMS_OUTPUT.PUT_LINE('SALARY : ' || SALARY);
END;
--LOCAL AND GLOBAL


DECLARE --OUTER BLOCK
NUM_1 INT:=10; --GLOBAL VAR

BEGIN
 DBMS_OUTPUT.PUT_LINE('VALUE OF GLOBAL' ||NUM_1);
DECLARE --INNER BLOCK
   NUM_1 INT:=500;
   BEGIN
   
   DBMS_OUTPUT.PUT_LINE('VALUE OF THE LOCAL'||NUM_1); 
   END;
END;