create table employee
(
f_name  char(10),
last_name  char(10),
emp_id    int,
salary    int,
department  char(3),
loc        varchar(10)
);
 
INSERT INTO EMPLOYEE VALUES('Jack','Hills',101,10000,'CSE','Delhi');
INSERT INTO EMPLOYEE VALUES('Rach','Green',11,15000,'CIV','UK');
INSERT INTO EMPLOYEE VALUES('Ross','Miller',111,5000,'CSE','Mumbai');
INSERT INTO EMPLOYEE VALUES('Jamie','Hills',121,25000,'IT','Delhi');

---------------------ARITHMETIC OPERATORS--

SELECT F_NAME,EMP_ID, SALARY+1000 "UPDATED_SALARY" FROM EMPLOYEE;
Update employee
Set salary=SALARY+1000
Where emp_id=111;

SELECT F_NAME, EMP_ID, SALARY*2 "UPDATED SALARY" FROM EMPLOYEE;

SELECT -3 "VALUE" FROM DUAL;
SELECT 3*2 FROM DUAL;

Update employee

Set salary=-SALARY

Where emp_id=111;
------------------------CHARACTER OPERATOR
-------concatenate a string

SELECT 'Name of the employee is: '|| UPPER(F_NAME) FROM EMPLOYEE;

------------------Comparison Operator
select * from employee;

SELECT F_NAME "NAME", EMP_ID, DEPARTMENT, SALARY
FROM EMPLOYEE
WHERE SALARY=25000;

SELECT* FROM EMPLOYEE
WHERE DEPARTMENT='CSE';
SELECT F_NAME, LAST_NAME, EMP_ID
FROM EMPLOYEE
WHERE SALARY>=25000;

SELECT F_NAME, LAST_NAME, EMP_ID
FROM EMPLOYEE
WHERE SALARY<250000;

SELECT F_NAME "NAME" FROM EMPLOYEE WHERE SALARY!=10000;
SELECT F_NAME "NAME" FROM EMPLOYEE WHERE SALARY^=10000;
SELECT F_NAME "NAME" FROM EMPLOYEE WHERE SALARY <> 10000;

SELECT * FROM EMPLOYEE
WHERE LOC IN ('Delhi', 'mumbai');

SELECT * FROM EMPLOYEE
WHERE DEPARTMENT IN ('CSE', 'IT', 'CIV');

SELECT F_NAME FROM EMPLOYEE
WHERE LOC IS NULL;

SELECT * FROM EMPLOYEE
WHERE SALARY IN (25000, 65000,6000);

SELECT * FROM EMPLOYEE
WHERE SALARY BETWEEN 10000 AND 50000;

---------------------------LOGICAL OPERATORS AND OR NOT

SELECT F_NAME FROM EMPLOYEE
WHERE NOT (LOC IS NULL);

SELECT * FROM EMPLOYEE
WHERE DEPARTMENT='CSE' AND LOC='Mumbai';

SELECT * FROM EMPLOYEE
WHERE DEPARTMENT='CSE' OR LOC='Munadi';

SELECT * FROM EMPLOYEE
WHERE DEPARTMENT ='CSE' AND NOT (SALARY <10000);

select sysdate from dual;
SELECT SYSTIMESTAMP FROM DUAL;

SELECT TO_DATE('January 26, 1996', 'Month dd YYYY') FROM DUAL;

SELECT LEAST(100, 200,15), GREATEST (100,200,15) FROM DUAL;