CREATE TABLE PERSONS 
(
PERSONID INT NOT NULL,
FIRSTNAME VARCHAR(20) NOT NULL,
AGE INT DEFAULT 18,
LOCATION VARCHAR(20),
PRIMARY KEY (PERSONID)
);

CREATE TABLE ORDERS
(
ORDERID INT NOT NULL,
ORDERNAME varchar(20),
PERSONID INT,
PRIMARY KEY(ORDERID)
);
INSERT INTO PERSONS VALUES(1,'MIKE',25,'LUDHIANA');
INSERT INTO PERSONS VALUES(2,'ANNA',15,'DELHI');
INSERT INTO PERSONS VALUES(3,'DANIEL',22,'UK');
INSERT INTO PERSONS VALUES(4,'JACK',25,'CANADA');

INSERT INTO ORDERS VALUES(100,'BOOKS',1);

INSERT INTO ORDERS VALUES(100,'TABLE',2);

INSERT INTO ORDERS VALUES(100,'PLANTS',5);

INSERT INTO ORDERS VALUES(100,'BOOKS',3);

select * FROM PERSONS;
SELECT * FROM ORDERS;

--INNER JOIN
SELECT PERSONS.PERSONID, PERSONS.FIRSTAME,PPERSONS.LOCATION, ORDERS.ORDERNAME, ORDERS.ORDERID
FROM ORDERS
INNER JOIN PERSONS
ON ORDERS.PERSONID=PERSONS.PERSONID
ORDER BY ORDERID;

--LEFT JOIN
--RETURNS ALL ROWS FROM LEFT TABLE AND THE MATCHING ROWS FROM RIGHT TABLE NO MATCH THEN RESULT WILL BE


SELECT PERSONS.PERSONID, PERSONS.FIRSTNAME,PERSONS.LOCATION,ORDERS.ORDERNAME
FROM PERSONS
LEFT JOIN PERSONS
ON ORDERS.PERSONID=PERSONS.PERSONID
ORDER BY ORDERID;

SELECT ORDERS.PERSONID, PERSONS.FIRSTNAME,PERSONS.LOCATION,ORDERS.ORDERNAME
FROM ORDERS
LEFT JOIN PERSONS
ON ORDERS.PERSONID=PERSONS.PERSONID
ORDER BY ORDERID;

--RIGHT JOIN
--RETURNS ALL ROS FROM RIGHT TABLE AND THE MATCHING ENTRIES FROM LEFT TABLE. IN THE LEFT TABLE THEN NULL 

SELECT PERSONS.PERSONID, PERSONS.FIRSTNAME,PERSONS.LOCATION,ORDERS.ORDERNAME,ORDERS.ORDERID
FROM ORDERS
RIGHT JOIN PERSONS
ON ORDERS.PERSONID=PERSONS.PERSONID
ORDER BY PERSONID;

--FULL JOIN
SELECT ORDERS.PERSONID "SECONDID",PERSONS.PERSONID, PERSONS.FIRSTNAME,PERSONS.LOCATION,ORDERS.ORDERNAME,ORDERS.ORDERID
FROM ORDERS
FULL JOIN PERSONS
ON ORDERS.PERSONID=PERSONS.PERSONID
ORDER BY PERSONID;

--SALESMAN(SID,NAME,CITY,SALARY)
--CUSTOMERS(CID,C_NAME,CITY,SPENDING,SID)

--DISPLAY A LIST OF CUSTOMERS WITH NAME,CITY,SPENDING,ORDER NO, SALESMAN NAME,SID
--WHOSE SPENDING WAS BETWEEN 10,000 TO 50,000